export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOADING_STARTED = 'LOADING_STARTED';
export const LOG_OUT = 'LOG_OUT';

export const LOADING_SELLABLE_STARTED = 'LOADING_SELLABLE_STARTED';
export const FETCH_SELLABLE_SUCCESS = 'FETCH_SELLABLE_SUCCESS';
export const FETCH_SELLABLE_FAIL = 'FETCH_SELLABLE_FAIL';

export const LOADING_SINGLE_ITEM = 'LOADING_SINGLE_ITEM';
export const FETCH_SINGLE_ITEM_SUCCESS = 'FETCH_SINGLE_ITEM_SUCCESS';
export const FETCH_SINGLE_ITEM_FAIL = 'FETCH_SINGLE_ITEM_FAIL';

export const LOADING_SINGLE_USER = 'LOADING_SINGLE_USER';
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS';
export const FETCH_SINGLE_USER_FAIL = 'FETCH_SINGLE_USER_FAIL';
